apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::032183660190:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1INYHMK5QR21O
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::032183660190:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-04T10:16:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1404"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9a41d00e-2f35-4636-bc6c-9aabddf57670

